### ISSUE TITLE
Project not setting up correctly

### ISSUE THREAD

**Issue by Shubbu03** [pvarentsov/typescript-clean-architecture#30]
<img width="1440" alt="Screenshot 2023-08-23 at 3 55 11 PM" src="https://github.com/pvarentsov/typescript-clean-architecture/assets/76101994/18f9453e-a942-4f63-83a1-1cdf8092489d">

I tried building and setting up again but this continues...

**Comment by Scandianis** [comment]
You have to set the environment variables as stated in README.md:

* **Configuring**
  
    Configuring is based on the environment variables. All environment variables must be exposed before starting the application.

**Comment by Shubbu03** [comment]
Yeah, i was able to do it and also made some changes for my usecase also. Thanks for this amazing repo,really helpful✌️
